apiVersion: apps/v1
kind: Deployment
metadata:
  name: paytrackr
  namespace: paytrackr  # kubernetes.namespace
  labels:
    app: paytrackr
    version: v1
spec:
  replicas: 2  # kubernetes.app_replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: paytrackr
  template:
    metadata:
      labels:
        app: paytrackr
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"  # app.port
    spec:
      containers:
      - name: paytrackr
        image: baltzar1994/paytrackr:latest  # app.docker_registry/app.docker_image:app.docker_tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080  # app.port
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: paytrackr-config
        - secretRef:
            name: paytrackr-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          #runAsNonRoot: true
          readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1000