apiVersion: v1
kind: Service
metadata:
  name: paytrackr-service
  namespace: paytrackr  # kubernetes.namespace
  labels:
    app: paytrackr
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"  # app.port
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080  # app.port
    protocol: TCP
    name: http
  selector:
    app: paytrackr
